$:
  vscode:
    - runner:
        cpus: 4
      docker:
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      stages:
        - name: 安装依赖
          script: 
            - npm install -g pnpm
            - pnpm i